resources:
  - https://raw.githubusercontent.com/flanksource/logs-exporter/v0.1.3/config/deploy/base.yml
images:
  - name: flanksource/logs-exporter
    newName: docker.io/flanksource/logs-exporter
    newTag: "{{.logsExporter.version | default "v0.1.3"}}"
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: logs-exporter-controller-manager
      namespace: platform-system
    spec:
      template:
        spec:
          containers:
            - name: manager
              args:
                - --metrics-addr=0.0.0.0:8080
                - "--sync-period={{ .templateOperator.syncPeriod | default \"5m\" }}"
              resources:
                limits:
                  cpu: 150m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 150Mi