run:
  # # default concurrency is a available CPU number
  # concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

  skip-dirs:
    - ./pkg/k8s/etcd
    - ./pkg/k8s/drain
    - ./pkg/k8s/proxy
  skip-files: []

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  gofmt:
    simplify: false

# Exclude konfigadm-template.yml from linting
# until konfigadm is modified to allow .yaml files
# see https://github.com/flanksource/konfigadm/pull/62
# and
# https://github.com/flanksource/konfigadm/blob/98ccbc8add3bbafdb6f488077c3f2f763d42bcb0/pkg/types/config.go#L155-L159
skip-files:
  - test/fixtures/konfigadm-template.yml
