apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: canary-checker
  name: canary-checker-sa
  namespace: platform-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: canary-checker-role
rules:
  - apiGroups:
      - canaries.flanksource.com
    resources:
      - canaries
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - canaries.flanksource.com
    resources:
      - canaries/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - services
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: canary-checker-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: canary-checker-role
subjects:
  - kind: ServiceAccount
    name: canary-checker-sa
    namespace: platform-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: canary-checker
  name: canary-checker
  namespace: platform-system
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    control-plane: canary-checker
---
apiVersion: scheduling.k8s.io/v1
description: This priority class should be used for canary pods only.
kind: PriorityClass
metadata:
  name: canary-checker-priority
value: -1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: canary-checker
  name: canary-checker
  namespace: platform-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: canary-checker
  template:
    metadata:
      labels:
        control-plane: canary-checker
      annotations:
        com.flanksource.infra.logs/processors.0.drop_event.when.contains.message: patching
        com.flanksource.infra.logs/processors.1.drop_event.when.contains.message: "[pod/canary] request completed with 503, expected [200 201 202], retrying"
        com.flanksource.infra.logs/processors.2.drop_event.when.contains.message: Requeue reconciliation
        com.flanksource.infra.logs/processors.3.drop_event.when.contains.message: Successfully Reconciled
    spec:
      containers:
        - args:
            - operator
            - -v
            - --httpPort
            - "8080"
            {{ range $server := .canaryChecker.aggregateServers }}
            - --aggregateServers
            - {{$server}}
            {{ end }}
          command:
            - /app/canary-checker
          env:
            - name: DOCKER_API_VERSION
              value: "1.39"
          image: docker.io/flanksource/canary-checker:{{.canaryChecker.version | default "v0.12.2"}}
          name: canary-checker
          ports:
            - name: metrics
              containerPort: 8080
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - CAP_NET_RAW
            privileged: true
            runAsUser: 0
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: dockersock
            - mountPath: /run/containerd/containerd.sock
              name: containerdsock
      serviceAccountName: canary-checker-sa
      terminationGracePeriodSeconds: 10
      volumes:
        - hostPath:
            path: /var/run/docker.sock
            type: ""
          name: dockersock
        - name: containerdsock
          hostPath:
            path: /run/containerd/containerd.sock
            type: ""
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: canary-checker
  name: canary-checker-monitor
  namespace: platform-system
spec:
  endpoints:
    - interval: 30s
      targetPort: 8080
  namespaceSelector:
    matchNames:
      - platform-system
  selector:
    matchLabels:
      control-plane: canary-checker
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: canary-checker
  namespace: platform-system
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - canaries.{{.domain}}
      secretName: canary-tls
  rules:
    - host: canaries.{{.domain}}
      http:
        paths:
          - backend:
              serviceName: canary-checker
              servicePort: 8080
