apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: canary
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: canary
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: canary-config
      containers:
        - name: canary
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          image: "flanksource/canary-checker:v0.8.3"
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          command:
            - "/app/canary-checker"
          args:
            - serve
            - --configfile
            - "/etc/config/canary-config.yaml"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: canary
  namespace: monitoring
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: canary

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: canary
  namespace: monitoring
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: canary-tls
      hosts:
        - canary.{{.domain}}
  rules:
    - host: canary.{{.domain}}
      http:
        paths:
          - backend:
              serviceName: canary
              servicePort: 8080