apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux
  namespace: kube-system
  labels:
    app: flux
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app: flux
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - targetPort: 9402
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-flux-rules
  namespace: kube-system
spec:
  groups:
  - name: flux.rules
    rules:
      - alert: FluxSyncAttemptFailed
        annotations:
          description:
            Flux failed attempting to sync due to an error connecting to Git or an invalid/duplicate manifest
          summary: Flux Sync Attempt Failed
        expr: |
          delta(flux_daemon_sync_duration_seconds_count{success='true'}[6m]) < 1
        for: 1m
        labels:
          severity: warning
      - alert: FluxApplyFailure
        annotations:
          description:
            Flux failed to apply manifests due to errors return by api server
          summary: Flux Apply Failed
        expr: |
          flux_daemon_sync_manifests{success='false'} > 0
        for: 1m
        labels:
          severity: warning
