apiVersion: v1
kind: ConfigMap
metadata:
  name: journalbeat-config
  namespace: platform-system
  labels:
    k8s-app: journalbeat
data:
  journalbeat.yml: |-
    fields:
      cluster: "{{ .name }}"

    journalbeat.inputs:
    - paths: ["/var/log/journal"]
      seek: cursor

    setup.dashboards.enabled: false
    setup.kibana:
      host: "{{ .packetbeat.kibana.url }}:{{ .packetbeat.kibana.port }}"
      username: ${ELASTIC_USERNAME}
      password: ${ELASTIC_PASSWORD}
      protocol: https
      ssl.verification_mode: none
      ssl.supported_protocols: [TLSv1.2, TLSv1.3]

    processors:
    - add_cloud_metadata: ~
    - add_kubernetes_metadata:
        in_cluster: true
        default_indexers.enabled: false
        default_matchers.enabled: false
        indexers:
          - container:
        matchers:
          - fields:
              lookup_fields: ["container.id"]
    - drop_event:
        when:
          equals:
            # Ignore auditd
            syslog.identifier: audit
    output.elasticsearch:
      hosts: ['${ELASTIC_URL}']
      username: ${ELASTIC_USERNAME}
      password: ${ELASTIC_PASSWORD}
      protocol: https
      ssl.verification_mode: none
      ssl.supported_protocols: [TLSv1.2, TLSv1.3]
      ilm.enabled: true

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: journalbeat
  namespace: platform-system
  labels:
    k8s-app: journalbeat
spec:
  selector:
    matchLabels:
      k8s-app: journalbeat
  template:
    metadata:
      labels:
        k8s-app: journalbeat
    spec:
      serviceAccountName: journalbeat
      terminationGracePeriodSeconds: 30
      containers:
        - name: journalbeat
          image: docker.elastic.co/beats/journalbeat:{{ .journalbeat.version }}
          args: [
            "-c", "/etc/journalbeat.yml",
            "-e",
          ]
          envFrom:
            - secretRef:
                name: elastic-infra
                optional: true
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /etc/journalbeat.yml
              readOnly: true
              subPath: journalbeat.yml
            - name: data
              mountPath: /usr/share/journalbeat/data
            - name: varlogjournal
              mountPath: /var/log/journal
              readOnly: true
            - name: machineid
              mountPath: /etc/machineid
              readOnly: true
            - name: systemd
              mountPath: /run/systemd
              readOnly: true
      volumes:
        - name: config
          configMap:
            defaultMode: 0600
            name: journalbeat-config
        - name: varlogjournal
          hostPath:
            path: /var/log/journal
        - name: machineid
          hostPath:
            path: /etc/machine-id
        - name: systemd
          hostPath:
            path: /run/systemd
        - name: data
          emptyDir: {}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: journalbeat
subjects:
  - kind: ServiceAccount
    name: journalbeat
    namespace: platform-system
roleRef:
  kind: ClusterRole
  name: journalbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: journalbeat
  labels:
    k8s-app: journalbeat
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: journalbeat
  namespace: platform-system
  labels:
    k8s-app: journalbeat