---
{{/* If external clusters are specified for kube-web-view            */}}
{{/* this template will be applied to them to configure the RBAC for */}}
{{/* the reporting user                                              */}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "kube-web-view-{{ .name }}"
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs: [list, get]
  - nonResourceURLs:
      - '*'
    verbs: [list, get]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "kube-web-view-{{ .name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kube-web-view-{{ .name }}"
subjects:
  - kind: User
    name: "kube-web-view"
    apiGroup: rbac.authorization.k8s.io