---
  {{/* If external clusters are specified for kube-resource-report     */}}
  {{/* this template will be applied to them to configure the RBAC for */}}
  {{/* the reporting user                                              */}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "external-kube-resource-report-{{ .name }}"
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "namespaces", "services"]
    verbs:
      - get
      - list
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs:
      - list
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources: ["services/proxy"]
    resourceNames: ["heapster"]
    verbs:
      - get
  # allow reading VPAs to get resource recommendations
  - apiGroups: ["autoscaling.k8s.io"]
    resources: ["verticalpodautoscalers"]
    verbs:
      - get
      - list
  # allow reading Deployments and StatefulSets to get matching Pods for VPAs
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets", "daemonsets"]
    verbs:
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "external-kube-resource-report-{{ .name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "external-kube-resource-report-{{ .name }}"
subjects:
  - kind: User
    name: "kube-resource-report"
    apiGroup: rbac.authorization.k8s.io

