filebeat:
  inputs:
    - type: log
      paths:
        - /var/log/modsecurity/modsec_audit.log
  config:
    modules:
      path: /usr/share/filebeat/modules.d/*.yml
      reload:
        enabled: true
  processors:
    - dissect:
        tokenizer: "%{message}"
        target_prefix: ""
        ignore_failure: true
output.elasticsearch:
  hosts: ['${ELASTIC_URL}']
  username: '${ELASTIC_USERNAME}'
  password: '${ELASTIC_PASSWORD}'
  ssl:
    supported_protocols: ['TLSv1.2', 'TLSv1.3']
    verification_mode: {{ sslMode }}
