filebeat:
  inputs:
    - type: log
      paths:
        - /var/log/modsecurity/modsec_audit.log
      json.keys_under_root: true
  config:
    modules:
      path: /usr/share/filebeat/modules.d/*.yml
      reload:
        enabled: true

output.elasticsearch:
  hosts: ['${ELASTIC_URL}']
  username: '${ELASTIC_USERNAME}'
  password: '${ELASTIC_PASSWORD}'
  ssl:
    supported_protocols: ['TLSv1.2', 'TLSv1.3']
    verification_mode: '$sslMode$'
{{- if ne .nginx.modsecurity.index "" }}
  index: '{{.nginx.modsecurity.index }}-%{[agent.version]}-%{+yyyy.MM.dd}'
setup:
  template:
    name: '{{.nginx.modsecurity.index }}'
    pattern: '{{.nginx.modsecurity.index }}-*'
    enabled: false
  ilm:
    rollover_alias: '{{.nginx.modsecurity.index }}-%{[agent.version]}'
{{ end }}
