apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          args:
            - "-upstream=file:///dev/null"
            - "-http-address=0.0.0.0:4180"
            - "-whitelist-domain=.{{.domain}}"
            - "-cookie-domain=.{{.domain}}"
            - "-provider=oidc"
            - "-provider-display-name=Dex"
            - "-client-id=kubernetes"
            - "-client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0"
            - "-redirect-url=https://oauth2.{{.domain}}/oauth2/callback"
            - "-oidc-issuer-url=https://dex.{{.domain}}"
            - "-oidc-group={{.oauth2Proxy.oidcGroup}}"
            - "-skip-oidc-discovery"
            - "-login-url=https://dex.{{.domain}}/auth"
            - "-redeem-url=https://dex.dex.svc:443/token"
            - "-ssl-insecure-skip-verify"
            - "-oidc-jwks-url=https://dex.dex.svc/keys"
            - "-cookie-secure=true"
            - "-email-domain=*"
            - "--pass-authorization-header=true"
            - "--pass-host-header=true"
            - "--pass-access-token=true"
            - "--set-xauthrequest=true"
            - "--set-authorization-header=true"
            - "--request-logging=true"
          env:
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: "{{.oauth2Proxy.cookieSecret}}"
          image: flanksource/oauth2_proxy:{{.oauth2Proxy.version}}
          resources:
            requests:
              cpu: 25m
              memory: 100Mi
            limits:
              memory: 512Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 4180
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: ingress-nginx
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: ingress-nginx
spec:
  rules:
    - host: oauth2.{{.domain}}
      http:
        paths:
          - backend:
              serviceName: oauth2-proxy
              servicePort: 4180
            path: /oauth2
  tls:
    - hosts:
        - oauth2.{{.domain}}
