apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-group
subjects:
  - kind: Group
    name: "{{ .ldap.adminGroup }}"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-creator
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - get
      - list
      - create
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "apps"
      - "rbac.authorization.k8s.io"
      - "networking.k8s.io"
      - autoscaling
    resources:
      - deployments
      - services
      - ingresses
      - configmaps
      - roles
      - rolebindings
      - persistentvolumeclaims
      - serviceaccounts
      - secrets
      - pods
      - pods/exec
      - pods/list
      - pods/portforward
      - jobs
      - resourceqoutas
      - replicasets
      - horizontalpodautoscalers
    verbs: ["*"]