{{ if .registryCredentials.dockerRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds-dpr
  namespace: {{ .registryCredentials.namespace }}
  labels:
    app: registry-creds
    kubernetes.io/minikube-addons: registry-creds
    cloud: private
data:
  DOCKER_PRIVATE_REGISTRY_SERVER: {{ .registryCredentials.dockerRegistry.server | base64.Encode }}
  DOCKER_PRIVATE_REGISTRY_USER: {{ .registryCredentials.dockerRegistry.username | base64.Encode }}
  DOCKER_PRIVATE_REGISTRY_PASSWORD: {{ .registryCredentials.dockerRegistry.password | base64.Encode }}
type: Opaque
---
{{ end }}
{{ if .registryCredentials.aws.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds-ecr
  namespace: {{ .registryCredentials.namespace }}
  labels:
    app: registry-creds
    kubernetes.io/minikube-addons: registry-creds
    cloud: ecr
data:
  AWS_ACCESS_KEY_ID: {{ .registryCredentials.aws.accessKey | base64.Encode }}
  AWS_SECRET_ACCESS_KEY: {{ .registryCredentials.aws.secretKey| base64.Encode }}
  AWS_SESSION_TOKEN: {{ .registryCredentials.aws.sessionToken | base64.Encode }}
  aws-account: {{ .registryCredentials.aws.account | base64.Encode }}
  aws-region: {{ .registryCredentials.aws.region | base64.Encode }}
  aws-assume-role: {{ .registryCredentials.aws.assumeRole | base64.Encode }}
type: Opaque
---
{{ end }}
{{ if .registryCredentials.gcr.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds-gcr
  namespace: {{ .registryCredentials.namespace }}
  labels:
    app: registry-creds
    kubernetes.io/minikube-addons: registry-creds
    cloud: gcr
data:
  application_default_credentials.json: {{ .registryCredentials.gcr.applicationCredentials | base64.Encode }}
  gcrurl: {{ .registryCredentials.gcr.url | base64.Encode }}
type: Opaque
---
{{ end }}
{{ if .registryCredentials.azure.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds-acr
  namespace: {{ .registryCredentials.namespace }}
  labels:
    app: registry-creds
    kubernetes.io/minikube-addons: registry-creds
    cloud: acr
data:
  ACR_URL: {{ .registryCredentials.azure.url | base64.Encode }}
  ACR_CLIENT_ID: {{ .registryCredentials.azure.clientId | base64.Encode }}
  ACR_PASSWORD: {{ .registryCredentials.azure.password| base64.Encode }}
type: Opaque
{{ end }}