apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: monitoring
  labels:
    k8s-app: pushgateway
spec:
  selector:
    k8s-app: pushgateway
  ports:
    - name: http
      protocol: TCP
      port: 9091

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: pushgateway
  template:
    metadata:
      name: pushgateway
      labels:
        k8s-app: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: "prom/pushgateway:{{.monitoring.pushGateway.version}}"
          ports:
            - name: web
              containerPort: 9091
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    k8s-app: pushgateway
  name: pushgateway
  namespace: monitoring
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: pushgateway.{{.domain}}
      http:
        paths:
          - backend:
              service:
                name: pushgateway
                port:
                  number: 9091
            pathType: ImplementationSpecific
  tls:
    - secretName: pushgateway-tls
      hosts:
        - pushgateway.{{.domain}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 5s
      path: /metrics
  selector:
    matchLabels:
      k8s-app: pushgateway
