apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
  labels:
    k8s-app: pushgateway
spec:
  selector:
    k8s-app: pushgateway
  type: NodePort
  ports:
    - name: pushgateway
      protocol: TCP
      port: 9091

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: pushgateway
  template:
    metadata:
      name: pushgateway
      labels:
        k8s-app: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:latest
          ports:
            - name: web
              containerPort: 9091
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    k8s-app: pushgateway
  name: pushgateway
  namespace: monitoring
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: pushgateway.{{.domain}}
      http:
        paths:
          - backend:
              serviceName: pushgateway
              servicePort: 9091
  tls:
    - secretName: pushgateway-tls
      hosts:
        - pushgateway.{{.domain}}
