apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store
  namespace: monitoring
  labels:
    app: thanos-store
spec:
  serviceName: "thanos-store"
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10902"
    spec:
      containers:
        - name: thanos-store
          image: docker.io/thanosio/thanos:{{.thanos.version}}
          args:
            - "store"
            - "--log.level=debug"
            - "--data-dir=/var/thanos/store"
            - "--objstore.config-file=/config/thanos.yaml"
            - --grpc-server-tls-cert=/ssl/client/tls.crt
            - --grpc-server-tls-key=/ssl/client/tls.key
            - --grpc-server-tls-client-ca=/ssl/ca/ca.crt
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          volumeMounts:
            - name: config
              mountPath: /config/
              readOnly: true
            - name: data
              mountPath: /var/thanos/store
            - name: thanos-cert
              mountPath: /ssl/client
            - name: thanos-ca-cert
              mountPath: /ssl/ca
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          secret:
            secretName: thanos-objstore-config
        - name: thanos-cert
          secret:
            secretName: thanos-cert
        - name: thanos-ca-cert
          secret:
            secretName: thanos-ca-cert

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: thanos-cert
  namespace: monitoring
spec:
  dnsNames:
    - thanos-store-grpc.monitoring.svc.cluster.local
    - thanos-store-grpc.monitoring.svc
    - thanos-store-http.monitoring.svc.cluster.local
    - thanos-store-http.monitoring.svc
    - thanos-query.monitoring.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: ingress-ca
  secretName: thanos-cert
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-grpc
  namespace: monitoring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 10901
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: thanos-store
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-http
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 10902
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: thanos-store
