apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
        - name: thanos-query
          image: docker.io/thanosio/thanos:{{.thanos.version}}
          args:
            - "query"
            - "--log.level=debug"
            - --store=thanos-store-grpc.monitoring.svc.cluster.local:10901
            - --store=thanos-sidecar.monitoring.svc.cluster.local:10901
            {{- range .thanos.clientSidecars}}
            - --store={{.}}
            {{- end}}
            - --query.replica-label=prometheus_replica
            - --grpc-server-tls-cert=/ssl/client/tls.crt
            - --grpc-server-tls-key=/ssl/client/tls.key
            - --grpc-server-tls-client-ca=/ssl/ca/ca.crt
            - --grpc-client-tls-secure
            - --grpc-client-tls-cert=/ssl/client/tls.crt
            - --grpc-client-tls-key=/ssl/client/tls.key
            - --grpc-client-tls-ca=/ssl/ca/ca.crt
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: thanos-query
              mountPath: /ssl/client
            - name: thanos-ca-cert
              mountPath: /ssl/ca
      volumes:
        - name: thanos-query
          secret:
            secretName: thanos-query
        - name: thanos-ca-cert
          secret:
            secretName: thanos-ca-cert

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: thanos-query
  namespace: monitoring
spec:
  dnsNames:
    - thanos-query.monitoring.svc.cluster.local
    - thanos-query.monitoring.svc
  issuerRef:
    kind: ClusterIssuer
    name: ingress-ca
  secretName: thanos-query
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
spec:
  jobLabel: thanos
  selector:
    matchLabels:
      app: thanos-query
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
    - port: http-query
      interval: 15s
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "10902"
    prometheus.io/scrape: "true"
  name: thanos-query
  labels:
    app: thanos-query
    jobLabel: thanos
  namespace: monitoring
spec:
  selector:
    app: thanos-query
  ports:
    - port: 9090
      protocol: TCP
      targetPort: http
      name: http-query
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: thanos-cluster
  namespace: monitoring
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: thanos.{{.domain}}
      http:
        paths:
          - path: /
            backend:
              serviceName: thanos-query
              servicePort: 9090
  tls:
    - secretName: thanos-tls
      hosts:
        - thanos.{{.domain}}
