namespace: platform-system
bases:
  - github.com/argoproj/argo-rollouts/manifests/base?ref=v0.10.2
  - github.com/argoproj/argo-rollouts/manifests/role?ref=v0.10.2
resources:
  - https://raw.githubusercontent.com/argoproj/argo-rollouts/v0.10.2/manifests/cluster-install/argo-rollouts-clusterrolebinding.yaml
images:
  - name: argoproj/argo-rollouts
    newName: docker.io/argoproj/argo-rollouts
    newTag: "{{.argoRollouts.version}}"
patchesStrategicMerge:
  - |-
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: argo-rollouts-clusterrolebinding
    subjects:
      - kind: ServiceAccount
        name: argo-rollouts
        namespace: platform-system
