namespace: elastic-system
resources:
  - https://download.elastic.co/downloads/eck/2.1.0/operator.yaml
  - certificate.yaml
images:
  - name: docker.elastic.co/eck/eck-operator
    newTag: "{{.eck.version}}"
patches:
  - path: delete-secret.yaml
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: elastic-system
