images:
  - name: quay.io/jetstack/cert-manager-controller
    newTag: "{{.certmanager.version}}"
  - name: quay.io/jetstack/cert-manager-cainjector
    newTag: "{{.certmanager.version}}"
  - name: quay.io/jetstack/cert-manager-webhook
    newTag: "{{.certmanager.version}}"
resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.11.0/cert-manager.yaml

patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cert-manager
        namespace: cert-manager
      spec:
        template:
          spec:
            containers:
              - name: cert-manager-controller
                args:
                  - --v=2
                  - --cluster-resource-namespace=$(POD_NAMESPACE)
                  - --default-issuer-name=ingress-ca
                  - --default-issuer-kind=ClusterIssuer
                  - --default-issuer-group=cert-manager.io
                  - --leader-election-namespace=kube-system
                  - --max-concurrent-challenges=60
  - patch: |-
      - op: add
        path: /rules/0
        value:
          apiGroups:
            - ""
          resources:
            - configmaps
          verbs:
            - get
            - update
            - patch
            - create
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      namespace: kube-system
  # Removes the CRD resources already present in manifests/crds/cert-manager.yaml
  # The name is required, but not used when matching
  - patch: |-
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: not-used
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
  - patch: |-
      $patch: delete
      apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      metadata:
        name: cert-manager-webhook
    target:
      group: admissionregistration.k8s.io
      version: v1
      kind: MutatingWebhookConfiguration
      name: cert-manager-webhook
  - patch: |-
      $patch: delete
      apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      metadata:
        name: cert-manager-webhook
    target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
