resources:
  - https://github.com/fluxcd/flux2/releases/download/v0.36.0/install.yaml
commonAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
images:
  - name: ghcr.io/fluxcd/helm-controller
    newTag: '{{.flux.helmControllerVersion | default "v0.26.0" }}'
  - name: ghcr.io/fluxcd/image-automation-controller
    newTag: '{{.flux.imageAutomationControllerVersion | default "v0.26.1" }}'
  - name: ghcr.io/fluxcd/image-reflector-controller
    newTag: '{{.flux.imageReflectorControllerVersion | default "v0.22.1" }}'
  - name: ghcr.io/fluxcd/kustomize-controller
    newTag: '{{.flux.kustomizeControllerVersion | default "v0.30.0" }}'
  - name: fluxcd/notification-controller
    newTag: '{{.flux.notificationControllerVersion | default "v0.28.0" }}'
    newName: ghcr.io/fluxcd/notification-controller
  - name: ghcr.io/fluxcd/source-controller
    newTag: '{{.flux.sourceControllerVersion | default "v0.31.0" }}'
