resources:
  - https://raw.githubusercontent.com/percona/percona-server-mongodb-operator/v1.6.0/deploy/operator.yaml
  - rbac.yaml

patchesStrategicMerge:
  - operator-patch.yaml

images:
  - name: percona/percona-server-mongodb-operator
    newName: docker.io/percona/percona-server-mongodb-operator
    newTag: "{{.mongodbOperator.version}}"