apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-datastore
spec:
  template:
    spec:
      containers:
        - name: mongodb-datastore
          env:
            - name: MONGODB_DATABASE
              value: admin
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-keptn-secrets
                  key: MONGODB_USER_ADMIN_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-keptn-secrets
                  key: MONGODB_USER_ADMIN_PASSWORD
            - name: MONGODB_HOST
              value: mongodb+srv://mongodb-keptn-rs0.keptn.svc.cluster.local:27017