{
 "title": "Log counts",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Log count by cluster/namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elastic_documents_by_namespace_cluster_node) by (count_cluster, count_namespace)",
     "legendFormat": "{{count_cluster}}/{{count_namespace}}"
    }
   ]
  },
  {
   "title": "Log count by cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elastic_documents_by_namespace_cluster_node) by (count_cluster)",
     "legendFormat": "{{count_cluster}}"
    }
   ]
  },
  {
   "title": "Log count by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elastic_documents_by_namespace_cluster_node) by (count_node)",
     "legendFormat": "{{count_node}}"
    }
   ]
  },
  {
   "title": "Log count by namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elastic_documents_by_namespace_cluster_node) by (count_namespace)",
     "legendFormat": "{{count_namespace}}"
    }
   ]
  },
  {
   "title": "Journalbeat logs by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elastic_documents_by_process_cluster_node) by (count_node)",
     "legendFormat": "{{count_node}}"
    }
   ]
  },
  {
   "title": "Journalbeat logs by cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elastic_documents_by_process_cluster_node) by (count_cluster)",
     "legendFormat": "{{count_cluster}}"
    }
   ]
  },
  {
   "title": "Journalbeat logs by process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elastic_documents_by_process_cluster_node) by (count_process)",
     "legendFormat": "{{count_process}}"
    }
   ]
  },
  {
   "title": "Journalbeat logs by cluster/process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elastic_documents_by_process_cluster_node) by (count_cluster, count_process)",
     "legendFormat": "{{count_cluster}}/{{count_process}}"
    }
   ]
  }
 ]
}