{
 "title": "Kubernetes Netstat",
 "description": "Netstat Metrics for Kubernetes Cluster",
 "tags": [ "netstat" ],
 "time": { "from": "now-6h", "to": "now-5h" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_netstat_Tcp_PassiveOpens, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Net Utilisation (Bytes Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate1m{ instance=\"$node\"}",
     "legendFormat": "Receive"
    },
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate1m{ instance=\"$node\"}*-1",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Net Saturation (Drops Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "instance:node_network_receive_drop_excluding_lo:rate1m{ instance=\"$node\"}",
     "legendFormat": "Receive drops"
    },
    {
     "expr": "instance:node_network_transmit_drop_excluding_lo:rate1m{ instance=\"$node\"}",
     "legendFormat": "Transmit drops"
    }
   ]
  },
  { "title": "IP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "IP",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_CurrEstab{instance=~\"$node\"}[5m])",
     "legendFormat": "Established"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$node\"}[5m])",
     "legendFormat": "Retransmits"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=~\"$node\"}[5m])",
     "legendFormat": "Syn Fails"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{instance=~\"$node\"}[5m])",
     "legendFormat": "InErrs"
    },
    {
     "expr": "irate(node_netstat_Ip_FragFails{instance=~\"$node\"}[5m])",
     "legendFormat": "FragFails"
    },
    {
     "expr": "irate(node_netstat_Ip_FragOKs{instance=~\"$node\"}[5m])",
     "legendFormat": "FragOKs"
    },
    {
     "expr": "irate(node_netstat_Ip_InAddrErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "InAddrErrors"
    },
    {
     "expr": "irate(node_netstat_Ip_InDelivers{instance=~\"$node\"}[5m])",
     "legendFormat": "InDelivers"
    },
    {
     "expr": "irate(node_netstat_Ip_InDiscards{instance=~\"$node\"}[5m])",
     "legendFormat": "InDiscards"
    },
    {
     "expr": "irate(node_netstat_Ip_InHdrErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "InHdrErrors"
    },
    {
     "expr": "irate(node_netstat_Ip_InReceives{instance=~\"$node\"}[5m])",
     "legendFormat": "InReceives"
    },
    {
     "expr": "irate(node_netstat_Ip_InUnknownProtos{instance=~\"$node\"}[5m])",
     "legendFormat": "InUnknownProtos"
    },
    {
     "expr": "irate(node_netstat_Ip_OutNoRoutes{instance=~\"$node\"}[5m])",
     "legendFormat": "OutNoRoutes"
    },
    {
     "expr": "irate(node_netstat_Ip_OutRequests{instance=~\"$node\"}[5m])",
     "legendFormat": "OutRequests"
    },
    {
     "expr": "irate(node_netstat_Ip_ReasmFails{instance=~\"$node\"}[5m])",
     "legendFormat": "ReasmFails"
    },
    {
     "expr": "irate(node_netstat_Ip_ReasmOKs{instance=~\"$node\"}[5m])",
     "legendFormat": "ReasmOKs"
    },
    {
     "expr": "irate(node_netstat_Ip_ReasmReqds{instance=~\"$node\"}[5m])",
     "legendFormat": "ReasmReqds"
    },
    {
     "expr": "irate(node_netstat_Ip_ReasmTimeout{instance=~\"$node\"}[5m])",
     "legendFormat": "ReasmTimeout"
    }
   ]
  },
  {
   "title": "IP Extended Statistics - Octets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "IP EXT - Octets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InBcastOctets{instance=~\"$node\"}[5m])",
     "legendFormat": "InBcastOctets"
    },
    {
     "expr": "irate(node_netstat_IpExt_InMcastOctets{instance=~\"$node\"}[5m])",
     "legendFormat": "InMcastOctets"
    },
    {
     "expr": "irate(node_netstat_IpExt_InOctets{instance=~\"$node\"}[5m])",
     "legendFormat": "InOctets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutBcastOctets{instance=~\"$node\"}[5m])",
     "legendFormat": "OutBcastOctets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutMcastOctets{instance=~\"$node\"}[5m])",
     "legendFormat": "OutMcastOctets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutOctets{instance=~\"$node\"}[5m])",
     "legendFormat": "OutOctets"
    }
   ]
  },
  {
   "title": "IP Extended Statistics - Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "IP EXT - Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InBcastPkts{instance=~\"$node\"}[5m])",
     "legendFormat": "InBcastPkts"
    },
    {
     "expr": "irate(node_netstat_IpExt_InCEPkts{instance=~\"$node\"}[5m])",
     "legendFormat": "InCEPkts"
    },
    {
     "expr": "irate(node_netstat_IpExt_InECT0Pkts{instance=~\"$node\"}[5m])",
     "legendFormat": "InECT0Pkts"
    },
    {
     "expr": "irate(node_netstat_IpExt_InECT1Pkts{instance=~\"$node\"}[5m])",
     "legendFormat": "InECT1Pkts"
    },
    {
     "expr": "irate(node_netstat_IpExt_InMcastPkts{instance=~\"$node\"}[5m])",
     "legendFormat": "InMcastPkts"
    },
    {
     "expr": "irate(node_netstat_IpExt_InNoECTPkts{instance=~\"$node\"}[5m])",
     "legendFormat": "InNoECTPkts"
    },
    {
     "expr": "irate(node_netstat_IpExt_InTruncatedPkts{instance=~\"$node\"}[5m])",
     "legendFormat": "InTruncatedPkts"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutBcastPkts{instance=~\"$node\"}[5m])",
     "legendFormat": "OutBcastPkts"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutMcastPkts{instance=~\"$node\"}[5m])",
     "legendFormat": "OutMcastPkts"
    }
   ]
  },
  {
   "title": "IP Extended Statistics - Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "IP EXT - Other",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InCsumErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "InCsumErrors"
    },
    {
     "expr": "irate(node_netstat_IpExt_InNoRoutes{instance=~\"$node\"}[5m])",
     "legendFormat": "InNoRoutes"
    }
   ]
  },
  { "title": "TCP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "TCP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~\"$node\"}[5m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_AttemptFails{instance=~\"$node\"}[5m])",
     "legendFormat": "AttemptFails"
    },
    {
     "expr": "irate(node_netstat_Tcp_CurrEstab{instance=~\"$node\"}[5m])",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "irate(node_netstat_Tcp_EstabResets{instance=~\"$node\"}[5m])",
     "legendFormat": "EstabResets"
    },
    {
     "expr": "irate(node_netstat_Tcp_InCsumErros{instance=~\"$node\"}[5m])",
     "legendFormat": "InCsumErros"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{instance=~\"$node\"}[5m])",
     "legendFormat": "InErrs"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=~\"$node\"}[5m])",
     "legendFormat": "InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_MaxConn{instance=~\"$node\"}[5m])",
     "legendFormat": "MaxConn"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutRsts{instance=~\"$node\"}[5m])",
     "legendFormat": "OutRsts"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$node\"}[5m])",
     "legendFormat": "OutSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~\"$node\"}[5m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$node\"}[5m])",
     "legendFormat": "RetransSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_RtoAlgorithm{instance=~\"$node\"}[5m])",
     "legendFormat": "RtoAlgorithm"
    },
    {
     "expr": "irate(node_netstat_Tcp_RtoMax{instance=~\"$node\"}[5m])",
     "legendFormat": "RtoMax"
    },
    {
     "expr": "irate(node_netstat_Tcp_RtoMin{instance=~\"$node\"}[5m])",
     "legendFormat": "RtoMin"
    }
   ]
  },
  { "title": "TCP Extended Statistics 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "TCP EXT - 1",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ArpFilter{instance=~\"$node\"}[5m])",
     "legendFormat": "ArpFilter"
    },
    {
     "expr": "irate(node_netstat_TcpExt_BusyPollRxPackets{instance=~\"$node\"}[5m])",
     "legendFormat": "BusyPollRxPackets"
    },
    {
     "expr": "irate(node_netstat_TcpExt_DelayedACKLocked{instance=~\"$node\"}[5m])",
     "legendFormat": "DelayedACKLocked"
    },
    {
     "expr": "irate(node_netstat_TcpExt_DelayedACKLost{instance=~\"$node\"}[5m])",
     "legendFormat": "DelayedACKLost"
    },
    {
     "expr": "irate(node_netstat_TcpExt_DelayedACKs{instance=~\"$node\"}[5m])",
     "legendFormat": "DelayedACKs"
    },
    {
     "expr": "irate(node_netstat_TcpExt_EmbryonicRsts{instance=~\"$node\"}[5m])",
     "legendFormat": "EmbryonicRsts"
    },
    {
     "expr": "irate(node_netstat_TcpExt_IPReversePathFilter{instance=~\"$node\"}[5m])",
     "legendFormat": "IPReversePathFilter"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=~\"$node\"}[5m])",
     "legendFormat": "ListenDrops"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=~\"$node\"}[5m])",
     "legendFormat": "ListenOverflows"
    },
    {
     "expr": "irate(node_netstat_TcpExt_LockDroppedIcmps{instance=~\"$node\"}[5m])",
     "legendFormat": "LockDroppedIcmps"
    },
    {
     "expr": "irate(node_netstat_TcpExt_OfoPruned{instance=~\"$node\"}[5m])",
     "legendFormat": "OfoPruned"
    },
    {
     "expr": "irate(node_netstat_TcpExt_OutOfWindowIcmps{instance=~\"$node\"}[5m])",
     "legendFormat": "OutOfWindowIcmps"
    },
    {
     "expr": "irate(node_netstat_TcpExt_PAWSActive{instance=~\"$node\"}[5m])",
     "legendFormat": "PAWSActive"
    },
    {
     "expr": "irate(node_netstat_TcpExt_PAWSEstab{instance=~\"$node\"}[5m])",
     "legendFormat": "PAWSEstab"
    },
    {
     "expr": "irate(node_netstat_TcpExt_PAWSPassive{instance=~\"$node\"}[5m])",
     "legendFormat": "PAWSPassive"
    },
    {
     "expr": "irate(node_netstat_TcpExt_PruneCalled{instance=~\"$node\"}[5m])",
     "legendFormat": "PruneCalled"
    },
    {
     "expr": "irate(node_netstat_TcpExt_RcvPruned{instance=~\"$node\"}[5m])",
     "legendFormat": "RcvPruned"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=~\"$node\"}[5m])",
     "legendFormat": "SyncookiesFailed"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=~\"$node\"}[5m])",
     "legendFormat": "SyncookiesRecv"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=~\"$node\"}[5m])",
     "legendFormat": "SyncookiesSent"
    }
   ]
  },
  { "title": "TCP Extended Statistics 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "TCP EXT - 2",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPAbortFailed{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPAbortFailed"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPAbortOnClose{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPAbortOnClose"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPAbortOnData{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPAbortOnData"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPAbortOnLinger{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPAbortOnLinger"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPAbortOnMemory{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPAbortOnMemory"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPAbortOnTimeout{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPAbortOnTimeout"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPACKSkippedChallenge{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPACKSkippedChallenge"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPACKSkippedFinWait2{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPACKSkippedFinWait2"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPACKSkippedPAWS{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPACKSkippedPAWS"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPACKSkippedSeq{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPACKSkippedSeq"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPACKSkippedSynRecv{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPACKSkippedSynRecv"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPACKSkippedTimeWait{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPACKSkippedTimeWait"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPAutoCorking{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPAutoCorking"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPBacklogDrop{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPBacklogDrop"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPChallengeACK{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPChallengeACK"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDeferAcceptDrop{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPDeferAcceptDrop"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDirectCopyFromBacklog{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPDirectCopyFromBacklog"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDirectCopyFromPrequeue{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPDirectCopyFromPrequeue"
    }
   ]
  },
  { "title": "TCP Extended Statistics 3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "TCP EXT - 3",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKIgnoredNoUndo{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPDSACKIgnoredNoUndo"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKIgnoredOld{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPDSACKIgnoredOld"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKOfoRecv{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPDSACKOfoRecv"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKOfoSent{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPDSACKOfoSent"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKOldSent{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPDSACKOldSent"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKRecv{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPDSACKRecv"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKUndo{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPDSACKUndo"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFACKReorder{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPFACKReorder"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastOpenActive{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPFastOpenActive"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastOpenActiveFail{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPFastOpenActiveFail"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastOpenCookieReqd{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPFastOpenCookieReqd"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastOpenListenOverflow{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPFastOpenListenOverflow"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastOpenPassive{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPFastOpenPassive"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastOpenPassiveFail{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPFastOpenPassiveFail"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastRetrans{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPFastRetrans"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPForwardRetrans{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPForwardRetrans"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFromZeroWindowAdv{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPFromZeroWindowAdv"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFullUndo{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPFullUndo"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPHPAcks{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPHPAcks"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPHPHits{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPHPHits"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPHPHitsToUser{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPHPHitsToUser"
    }
   ]
  },
  { "title": "TCP Extended Statistics 4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "TCP EXT - 4",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPHystartDelayCwnd{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPHystartDelayCwnd"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPHystartDelayDetect{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPHystartDelayDetect"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPHystartTrainCwnd{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPHystartTrainCwnd"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPHystartTrainDetect{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPHystartTrainDetect"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPKeepAlive{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPKeepAlive"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPLossFailures{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPLossFailures"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPLossProbeRecovery{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPLossProbeRecovery"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPLossProbes{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPLossProbes"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPLossUndo{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPLossUndo"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPLostRetransmit{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPLostRetransmit"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPMD5NotFound{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPMD5NotFound"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPMD5Unexpected{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPMD5Unexpected"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPMemoryPressures{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPMemoryPressures"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPMinTTLDrop{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPMinTTLDrop"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPMTUPFail{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPMTUPFail"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPMTUPSuccess{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPMTUPSuccess"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPOFODrop{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPOFODrop"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPOFOMerge{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPOFOMerge"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPOFOQueue{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPOFOQueue"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPOrigDataSent{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPOrigDataSent"
    }
   ]
  },
  { "title": "TCP Extended Statistics 5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "TCP EXT - 5",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPPartialUndo{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPPartialUndo"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPPrequeued{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPPrequeued"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPPrequeueDropped{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPPrequeueDropped"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPPureAcks{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPPureAcks"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPRcvCoalesce{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPRcvCoalesce"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPRcvCollapsed{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPRcvCollapsed"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPRenoFailures{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPRenoFailures"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPRenoRecovery{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPRenoRecovery"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPRenoRecoveryFail{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPRenoRecoveryFail"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPRenoReorder{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPRenoReorder"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPReqQFullDoCookies{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPReqQFullDoCookies"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPReqQFullDrop{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPReqQFullDrop"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPRetransFail{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPRetransFail"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSACKDiscard{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSACKDiscard"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSackFailures{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSackFailures"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSackMerged{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSackMerged"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSackRecovery{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSackRecovery"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSackRecoveryFail{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSackRecoveryFail"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSACKRenegin{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSACKRenegin"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSACKReorder{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSACKReorder"
    }
   ]
  },
  { "title": "TCP Extended Statistics 6", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "TCP EXT - 6",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPSackShifted{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSackShifted"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSackShiftFallback{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSackShiftFallback"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSchedulerFailed{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSchedulerFailed"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSlowStartRetrans{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSlowStartRetrans"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSpuriousRTOs{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSpuriousRTOs"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSpuriousRtxHostQueues{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSpuriousRtxHostQueues"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSYNChallenge{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSYNChallenge"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPSynRetrans"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPTimeouts{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPTimeouts"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPTimeWaitOverflow{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPTimeWaitOverflow"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPToZeroWindowAdv{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPToZeroWindowAdv"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPTSReorder{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPTSReorder"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPWantZeroWindowAdv{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPWantZeroWindowAdv"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPWinProbe{instance=~\"$node\"}[5m])",
     "legendFormat": "TCPWinProbe"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TW{instance=~\"$node\"}[5m])",
     "legendFormat": "TW"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TWKilled{instance=~\"$node\"}[5m])",
     "legendFormat": "TWKilled"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TWRecycled{instance=~\"$node\"}[5m])",
     "legendFormat": "TWRecycled"
    }
   ]
  },
  { "title": "UDP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "UDP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_IgnoredMulti{instance=~\"$node\"}[5m])",
     "legendFormat": "IgnoredMulti"
    },
    {
     "expr": "irate(node_netstat_Udp_InCsumErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "InCsumErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node\"}[5m])",
     "legendFormat": "InDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node\"}[5m])",
     "legendFormat": "NoPorts"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node\"}[5m])",
     "legendFormat": "OutDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "RcvbufErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "SndbufErrors"
    }
   ]
  },
  { "title": "UDP Light Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "UDP LITE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_UdpLite_IgnoredMulti{instance=~\"$node\"}[5m])",
     "legendFormat": "IgnoredMulti"
    },
    {
     "expr": "irate(node_netstat_UdpLite_InCsumErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "InCsumErrors"
    },
    {
     "expr": "irate(node_netstat_UdpLite_InDatagrams{instance=~\"$node\"}[5m])",
     "legendFormat": "InDatagrams"
    },
    {
     "expr": "irate(node_netstat_UdpLite_InErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "InErrors"
    },
    {
     "expr": "irate(node_netstat_UdpLite_NoPorts{instance=~\"$node\"}[5m])",
     "legendFormat": "NoPorts"
    },
    {
     "expr": "irate(node_netstat_UdpLite_OutDatagrams{instance=~\"$node\"}[5m])",
     "legendFormat": "OutDatagrams"
    },
    {
     "expr": "irate(node_netstat_UdpLite_RcvbufErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "RcvbufErrors"
    },
    {
     "expr": "irate(node_netstat_UdpLite_SndbufErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "SndbufErrors"
    }
   ]
  }
 ]
}