apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: monitoring
type: Opaque
stringData:
  thanos.yaml: |-
    type: S3
    config:
      bucket: {{.thanos.bucket}}
      endpoint: {{.s3.endpoint | strings.TrimPrefix "http://" | strings.TrimPrefix "https://" }}
      {{- if .s3.endpoint | strings.HasPrefix "http://" }}
      insecure: true
      http_config:
        insecure_skip_verify: true
      {{- end}}
      {{- if .s3.region }}
      region: {{.s3.region}}
      {{- end }}
      {{- if .s3.access_key }}
      access_key: {{.s3.access_key}}
      secret_key: {{.s3.secret_key}}
      {{- end}}
